name: test

on:
  workflow_dispatch:

jobs:
  setup-node-files-input:
    name: Setup Node for ${{ matrix.node-version-file }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
        node-version-file: ['.nvmrc', '.node-version', 'none', '.n-node-version']
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: setup-node ${{ matrix.node-version-file }}
        uses: hkaur008/setup-node@pull209
        with:
          node-version-file: ${{ matrix.node-version-file }}
      - name: Node version
        run: node --version

  setup-node-files-input-and-node-version:
    name: Setup Node for ${{ matrix.node-version-file }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
        node-version-file: ['.npmrc', '.node-version', 'none', '.n-node-version']
        node-version: [12, 14, 17]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: setup-node ${{ matrix.node-version-file }}
        uses: hkaur008/setup-node@pull209
        with:
          node-version-file: ${{ matrix.node-version-file }}
          node-version: ${{ matrix.node-version }}
      - name: Node version
        run: node --version

  setup-node-node-version-input:
    name: Setup Node for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
        node-version: [12, 14, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-node ${{ matrix.node-version }}
        uses: hkaur008/setup-node@pull209
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node version
        run: node --version
  setup-node-default:
    name: Setup Node for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: hkaur008/setup-node@pull209
      - name: Node version
        run: node --version
