name: test

on:
  workflow_dispatch:

jobs:
  setup-java-major-versions:
    name: Setup Java for major versions ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        distribution: ['liberica']
        java-package: ['jdk', 'jre']
        java:
        - '11.x'
        - '16.x'
        - '17.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }}
        uses: RazorNd/setup-java@liberica
        with:
          java-version: ${{ matrix.java }}
          java-package: ${{ matrix.java-package }}
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-major-minor-versions:
    name: Setup Java for major minor versions ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        distribution: ['liberica']
        java-package: ['jdk', 'jre']
        java:
        - '8.0.x'
        - '11.0.x'
        - '16.0.x'
        - '17.0.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }}
        uses: RazorNd/setup-java@liberica
        with:
          java-version: ${{ matrix.java }}
          java-package: ${{ matrix.java-package }}
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version

  setup-java-ea-versions:
    name: Setup Java for ea versions ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        distribution: ['liberica']
        java-package: ['jdk', 'jre']
        java:
        - '11-ea'
        - '16-ea'
        - '17-ea'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup-java ${{ matrix.java }}
        uses: RazorNd/setup-java@liberica
        with:
          java-version: ${{ matrix.java }}
          java-package: ${{ matrix.java-package }}
          distribution: ${{ matrix.distribution }}
      - name: Java version
        run: java -version
