name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: dmitry-shibanov/setup-python@v-dmshib/prepare-cache-support
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Check setup.py
      run: |
        python setup.py check

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - run: |
        cacheDir=$(pip cache dir)
        echo "cacheDir is $cacheDir"
        ls $cacheDir
        ls /home/runner/.cache/pip
    - name: Black fmt
      run: |
        black . --check

    - name: Unittest
      run: |
        python -m unittest discover -s tests
        
    - name: Coverage
      run: |
        coverage run -m unittest discover
        coverage report

#   test-speed:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.8]

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: dmitry-shibanov/setup-python@v-dmshib/add-cache-support
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt
#           pip install -r requirements-speed.txt
#           pip install -r requirements-test.txt

#       - name: Unittest
#         run: |
#           python -m unittest discover -s tests
