name: test

on:
  workflow_dispatch:

jobs:
  python_utils_tests_page_0:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: pip-${{ env.pythonLocation }}-${{ hashFiles('**/requirements.txt') }} }}
          restore-keys: pip-${{ env.pythonLocation }}

      - name: Packages by default
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py pip==21.0.1
          pip freeze

      - name: Install apt dependencies
        run: |
          echo "PYTHONPATH=/usr/lib/python3/dist-packages" >> $GITHUB_ENV
          python --version
          sudo apt-get update
          sudo apt-get install gdal-bin
          python --version
          sudo apt-get install build-essential python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
          python --version
          sudo apt-get install libmapnik3.0 libmapnik-dev python3-mapnik
          python --version

      - name: After installing apt dependencies
        run: |
          python -V
          python -c "import os; print(os.environ['PATH'])"
          sudo python -V
          echo "with sudo"
          sudo python -c "import os; print(os.environ['PATH'])"
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python -V
          sudo python -V
          sudo python3 get-pip.py pip==21.0.1
          sudo pip freeze
